import org.jetbrains.changelog.Changelog
import org.jetbrains.gradle.ext.Gradle

plugins {
    id 'java'
    id 'scala'
    id 'java-library'
    id 'maven-publish'
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.4.1'
    id 'org.jetbrains.changelog' version '2.2.1'
    id 'xyz.wagyourtail.unimined' version '1.4.26-kappa'
}

apply from: 'gradle/scripts/helpers.gradle'

// Early Assertions
assertProperty 'mod_version'
assertProperty 'root_package'
assertProperty 'mod_name'

assertSubProperties 'use_access_transformer', 'access_transformer_locations'
assertSubProperties 'is_coremod', 'coremod_includes_mod', 'coremod_plugin_class_name'
assertSubProperties 'use_asset_mover', 'asset_mover_version'

setDefaultProperty 'generate_sources_jar', true, false
setDefaultProperty 'generate_javadocs_jar', true, false
setDefaultProperty 'minecraft_username', true, 'Developer'
setDefaultProperty 'extra_jvm_args', false, ''

version = propertyString('mod_version')
group = propertyString('root_package')

base {
    archivesName.set(propertyString('mod_name'))
}

scala {
    scalaVersion = '3.8.2'
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
    if (propertyBool('generate_sources_jar')) {
        withSourcesJar()
    }
    if (propertyBool('generate_javadocs_jar')) {
        withJavadocJar()
    }
}

configurations {
    embed
    contain
    implementation.extendsFrom(embed)
}

unimined.minecraft {
    version "1.12.2"

    mappings {
        mcp("stable", "39-1.12")
    }

    cleanroom {
        if (propertyBool('use_access_transformer')) {
            accessTransformer 'src/main/resources/META-INF/' +  propertyString('access_transformer_locations')
        }
        loader "0.5.17-alpha"
        runs.auth.username = minecraft_username
        runs.all {
            if (hasProperty("extra_jvm_args")) {
                jvmArgs(propertyString('extra_jvm_args'))
            }
            if (propertyBool('enable_foundation_debug')) {
                systemProperty("foundation.dump", "true")
                systemProperty("foundation.verbose", "true")
            }
            return
        }
    }


}

apply from: 'gradle/scripts/dependencies.gradle'

repositories {
    maven {
        name = 'CleanroomMC Maven'
        url = 'https://maven.cleanroommc.com'
    }
    maven {
        name = "outlandsReleases"
        url = "https://maven.arcseekers.com/releases"
    }
}

dependencies {
    if (propertyBool('use_asset_mover')) {
        implementation "com.cleanroommc:assetmover:${propertyString('asset_mover_version')}"
    }
}


processResources {

    inputs.property 'mod_version', propertyString('mod_version')

    def filterList = ['mcmod.info']

    filesMatching(filterList) { fcd ->
        fcd.expand(
                'mod_version': propertyString('mod_version'),
        )
    }

}

jar {
    archiveClassifier = 'deobf'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    if (configurations.contain.size() > 0) {
        into('/') {
            from configurations.contain
        }
    }
    doFirst{
        manifest {
            def attribute_map = [:]
            attribute_map['ModType'] = "CRL"
            if (configurations.contain.size() > 0) {
                attribute_map['ContainedDeps'] = configurations.contain.collect { it.name }.join(' ')
                attribute_map['NonModDeps'] = true
            }
            if (propertyBool('is_coremod')) {
                attribute_map['FMLCorePlugin'] = propertyString('coremod_plugin_class_name')
                if (propertyBool('coremod_includes_mod')) {
                    attribute_map['FMLCorePluginContainsFMLMod'] = true
                }
            }
            if (propertyBool('use_access_transformer')) {
                attribute_map['FMLAT'] = propertyString('access_transformer_locations')
            }
            attributes(attribute_map)
        }
    }
}

tasks.remapJar {
    archiveClassifier = 'universal'
    doFirst {
        logging.captureStandardOutput LogLevel.INFO
    }
    doLast {
        logging.captureStandardOutput LogLevel.QUIET
    }
}

tasks.withType(ScalaCompile).configureEach {
    //scalaCompileOptions.additionalParameters = ['-new-syntax', '-rewrite']
    //scalaCompileOptions.additionalParameters = ['-indent', '-rewrite']
    //scalaCompileOptions.additionalParameters = ['-source','3.8-migration', '-rewrite']
    //scalaCompileOptions.additionalParameters = ['-source','3.4-migration', '-rewrite']
    //scalaCompileOptions.additionalParameters = ['-source','3.5-migration', '-rewrite']
    //scalaCompileOptions.additionalParameters = ['-source','3.6-migration', '-rewrite']
    //scalaCompileOptions.additionalParameters = ['-source','future-migration', '-rewrite']
}


String parserChangelog() {
    if (!file('CHANGELOG.md').exists()) {
        throw new GradleException('publish_with_changelog is true, but CHANGELOG.md does not exist in the workspace!')
    }
    String parsedChangelog = changelog.renderItem(
            changelog.get(propertyString('mod_version')).withHeader(false).withEmptySections(false),
            Changelog.OutputType.MARKDOWN)
    if (parsedChangelog.isEmpty()) {
        throw new GradleException('publish_with_changelog is true, but the changelog for the latest version is empty!')
    }
    return parsedChangelog
}


tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}


apply from: 'gradle/scripts/publishing.gradle'
apply from: 'gradle/scripts/extra.gradle'
